def count_nucleotides(dna_string):
    # Count the occurrences of each nucleotide
    a = dna_string.count('A')
    c = dna_string.count('C')
    g = dna_string.count('G')
    t = dna_string.count('T')
    
    # Return the formatted space-separated string
    return f"{a} {c} {g} {t}"

# The Sample Dataset provided in the image
sample_dna = "TCATACGCTGTCGTTCTAACCCACGCACATACTAATAGATGTCGCGTGGATAAGTCACCTATCATCCTATATCTTTAGATGGGCTAAAATTGATCATCAGCCAATTCGTGTCACACGTGCTAAAAGGACCGTTTACAAGCCCACATACTTAGTACGGGCAGATCGCTCCCTTGATCTTGTATCTGAGGAAGCGCACAATAATATCAGGGACGAAACTCTTTTTCTCAGTACAGGTCGTCGCGAACACGGTAATGCATCCTTCCTTCTGCCCGATAACGGCATAGAGTCCGACAACTGTGAGGCCATATCTCCCTGTTGTATCTGCTGTGAAGGGGGGACATTTCGACCATAAAGCGCCCACAGCCTAGACCGTGATAATTCAGAGGTCAAGCGTCGTATAGGCTAAAGGGAAGAAGTGACGCTCTCCTTGCGTAGTATCTCCTGCACAAAGGGCTGGCCAATACGCGGTCAATGTCAACAACATCTTGTATGTTTACAAATCAGGTCCCAGTTGAATAAAGATGTATTAGTGCATTCACGTTATAAGGAAGGACCATTTATTATACCAATTAGCGTTGTTTCACCTGTTTCAGATGGTGTTAGGGTGACTGCGACCCTTCGTTATCAAGTACCAACCGGACCGCCCCACGCTCTCAGTCATACTCGGACTGAGTTTTTGGAGGATGCAGTTTTACTCGCTTTTGAGAAACTCTTTTCCAGTAACTGTTACGGGTCTTATCATTTTCACGGCCCTAACTGGAAGCGTCGTAATTGACCTCTAATACTGTGACGCTTGCCGGGCGGACCCGAACTACTAACACAGGCTGCGATGCGTGGTCCCAGAGCAGCCCGAGCTAAT
"

# Print the result
print(count_nucleotides(sample_dna))